DDelivery/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('homepage/', include('Homepage.urls')),
    path('users/', include('Users.urls')),
    path('delivery-system/', include('DS.urls')),
    path('driver/', include('Driver.urls')),
    path('gen-pdf/', include('GPDF.urls')),
    path('gen-xlsx/', include('GXLSX.urls'))
]

DS/urls.py
from django.urls import path

from . import views
from . import profile_view

app_name = 'DS_app'

urlpatterns = [
    path('homepage/', views.base_DS_page, name = 'DS_homepage'),
    path('order-in-delivery/<int:current_page>/', views.order_delivery, name = 'DS_order_in_delivery'),
    path('order-successful/<int:current_page>/', views.order_success, name = 'DS_order_success'),
    path('order-in-pending/<int:current_page>/<str:notificationMsg>/', views.order_in_pending, name = 'DS_order_pending'),
    path('order-need-delivery/<int:current_page>/', views.order_need_delivery, name = 'DS_order_need_delivery'),
    path('log-out/', views.log_out, name = 'DS_log_out'),
    path('static/', views.get_static, name = 'DS_get_static'),
    path('static-order-by-driver/<dateSearch>/<idDriver>/<CurrentPage>/<driver_name>/', views.get_static_ds_driver, name = 'DS_static_order_by_driver'),
    path('static-by-date/<int:CurrentPage>/<dateValue>/', views.get_static_ds_date, name = 'DS_static_by_date'),
    path('static-by-month/<int:CurrentPage>/<monthValue>/', views.get_static_month, name = 'DS_static_by_month'),
    path('static-by-year/<int:CurrentPage>/<yearValue>/', views.get_static_year, name = 'DS_static_by_year'),
    path('static-total-money-one-month/<monthValue>/<int:CurrentPage>/', views.total_money_one_month, name = 'DS_total_money_one_month'),
    path('static-total-money-one-day/<dayValue>/<int:CurrentPage>/', views.total_money_one_day, name = 'DS_total_money_one_day'),
    path('static-total-money-one-year/<yearValue>/<int:CurrentPage>/', views.total_money_one_year, name = 'DS_total_money_one_year'),
    path('search-order/', views.search_order, name = 'DS_search_order'),
    path('search-by-code-order/<int:CurrentPage>/<CodeOrder>/<msgNotification>/', views.searchOrderByCodeOrder, name = 'DS_search_order_by_code'),
    path('search-by-day/<int:CurrentPage>/<chooseDate>/', views.searchOrderDSByDay, name = 'DS_search_order_by_day'),
    path('search-by-month/<int:CurrentPage>/<chooseMonth>/', views.searchOrderDSByMonth, name = 'DS_search_order_by_month'),
    path('search-by-year/<int:CurrentPage>/<chooseYear>/', views.searchOrderDSByYear, name = 'DS_search_order_by_year'),
    path('search-by-tel/<telSender>/<telReceiver>/<int:CurrentPage>/', views.searchOrderDSByTel, name = 'DS_search_order_by_tel'),
    path('search-order-all/<int:CurrentPage>/', views.searchOrderDSAll, name = 'DS_search_order_all'),
    path('order-return/<int:CurrentPage>/', views.orderReturnDS, name = 'DS_order_return'),
    path('profile/homepage/', views.baseDSProfile, name ='DS_base_profile'),
]

DS/models.py
from django.db import models

# Create your models here.

DS/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
import datetime 
import locale

from . import exec_data
from . import get_inform_order
# Create your views here.

# @deliverySystem_blueprint.before_request
# def checkCurrentToken():
#     if 'tokenDeliveryWedDemo' not in session:
#         return redirect(url_for('loginAccountBp.loginAccount'))
#     load_dotenv()
#     secretKey = os.getenv('secret_key')
#     decodeToken = jwt.decode(session['tokenDeliveryWedDemo'], secretKey, algorithms = ["HS256"])

#     currentTime = datetime.now()
#     startTimeToken = datetime.strptime(decodeToken['startTimeTokenStr'], f'%d-%m-%Y %H:%M:%S')
#     endTimeToken = datetime.strptime(decodeToken['endTimeTokenStr'], f'%d-%m-%Y %H:%M:%S')

#     if currentTime > startTimeToken and currentTime < endTimeToken:
#         roleUserTemp = decodeToken['roleUser']
#         if roleUserTemp == 'DS':
#             session['roleUser'] = 'User'
#             session['idDS'] = decodeToken['idRoleUser']
#         else:
#             return "<p>You are not login at role user, so you can't access this page</p>"
#     else:
#         return redirect(url_for('loginAccountBp.loginAccount', notificationEndToken = True))


def base_DS_page(request):
    #     idDS = session['idDS']
    #     imageChart = drawChart.drawBarChartHomepage(idDS = idDS)
    #     totalMoneyChart = drawChart.drawTotalMoneyChart(idDS = idDS)
    #     statusOrderEachMonth = drawChart.drawChartOrderCreateEachMonth(idDS = idDS)
    #     len_order_fail = dsExecuteDatabase.orderReturn(idDS, 1, limitShowOrder)['len_all_order']
    #     chart_each_driver_order = drawChart.drawChartOrderEachDriver(idDS)

    #     return render_template('baseDeliverySystem.html', imageChartBase = imageChart, totalMoneyChart = totalMoneyChart, 
    #         statusOrderEachMonth = statusOrderEachMonth, len_order_fail = len_order_fail, status ='Homepage', chart_each_driver_order = chart_each_driver_order)
    return render(request, 'DS/base_ds.html')

# Show all order in Delivery, old name : deliveryInTransit, new name : order_delivery
def order_delivery(request, current_page = 1):
    id_ds = request.session.get('id_role_user_ddelivery', None)

    execute_database = exec_data.get_order_in_delivery(id_ds, current_page)
    all_order_delivery = execute_database[1]
    lst_driver = execute_database[2]

    all_inform = get_inform_order.get_information(all_order_delivery)
    # dictCountryShippingAddr = countTimeExits.countTimeExitsShippingAddr(allInform[0])
    # dictCountryDeliveryAddr = countTimeExits.countTimeExitsDeliveryAddr(allInform[1])
    # sumMoneyOrder = countTimeExits.sumMoneyAllOrder(all_order_delivery)      
    # dictDriverTimes = countTimeExits.countTimeExitsDriver(lst_driver)

    # dictDriverTimes = dictDriverTimes, sumMoneyOrder = sumMoneyOrder, dictCountryShippingAddr = dictCountryShippingAddr, dictCountryDeliveryAddr = dictCountryDeliveryAddr
    context_return = {'allOrderDelivery' : all_order_delivery, 'lstSender' : all_inform[0], 'lstReceiver' : all_inform[1], 'lstType' : all_inform[2], 'lstDriver' : lst_driver, 'paginationPage' : execute_database[0], 'CurrentPage' : current_page, 'len_all_order' : execute_database[3]}
    context_return['range_pagination_page'] = [iteration for iteration in range(1, execute_database[0] + 1)]

    return render(request, 'DS/order_in_delivery.html', context_return)
        
# Show all order in delivery success
def order_success(request, current_page = 1):
    id_ds = request.session.get('id_role_user_ddelivery', None)

    execute_database = exec_data.get_order_success(id_ds, current_page)
    lstDriver = execute_database[2]
    all_order_success = execute_database[1]

    all_inform = get_inform_order.get_information(all_order_success)

    # dictCountryShippingAddr = countTimeExits.countTimeExitsShippingAddr(all_inform[0])
    # dictCountryDeliveryAddr = countTimeExits.countTimeExitsDeliveryAddr(all_inform[1])
    # sumMoneyOrder = countTimeExits.sumMoneyAllOrder(all_order_success)
    # dictDriverTimes = countTimeExits.countTimeExitsDriver(lstDriver)
    
    # dictCountryShippingAddr = dictCountryShippingAddr, dictCountryDeliveryAddr = dictCountryDeliveryAddr, sumMoneyOrder = sumMoneyOrder, dictDriverTimes = dictDriverTimes
    context_return = {'allOrderSuccess' : all_order_success, 'lstSender' : all_inform[0], 'lstReceiver' : all_inform[1], 'lstType' : all_inform[2], 'lstDriver' : lstDriver, 'CurrentPage' : current_page, 'paginationPage' : execute_database[0], 'len_all_order' : execute_database[3]}

    context_return['range_pagination_page'] = [iteration for iteration in range(1, execute_database[0] + 1)]

    return render(request, 'DS/order_success.html', context_return)

# Show all order need delivery. DS will assign each other for driver
def order_in_pending(request, current_page = 1, notificationMsg = []):
    id_ds = request.session.get('id_role_user_ddelivery', None)

    execute_database = exec_data.get_order_pending(id_ds, current_page)
    all_driver = execute_database[2]
    all_order_pending = execute_database[1]
    len_all_order = execute_database[3]

    all_inform = get_inform_order.get_information(all_order_pending)

    notificationMsg = request.GET.getlist('notificationMsg')
    if request.method == 'POST':
        # if 'autoUpdateDriver' in request.form:
        #     return redirect(url_for('autoUpdateShipperDS.autoUpdateShipper'))

        lstMessageUpdate = []
        for index in range(0, len(all_order_pending)):
            eachOrderTemp = request.POST.get(f'updateShipper{index}', None)
            if eachOrderTemp == 'notValue':
                continue
            else:
                driverName = eachOrderTemp.split(",")[2]
                codeOrder = eachOrderTemp.split(",")[1]
                idDriver = int(eachOrderTemp.split(",")[0])

                message_update = exec_data.post_order_pending(id_ds, codeOrder, idDriver, driverName)
                lstMessageUpdate.append(message_update)
        return redirect('DS_app:DS_order_pending', current_page = 1, notificationMsg = lstMessageUpdate)
    # TODO
    # dictCountryShippingAddr = countTimeExits.countTimeExitsShippingAddr(allInform[0])
    # dictCountryDeliveryAddr = countTimeExits.countTimeExitsDeliveryAddr(allInform[1])
    # sumMoneyOrder = countTimeExits.sumMoneyAllOrder(all_product_need_delivery)
    context_return = {'all_order_pending' : all_order_pending, 'allDriver' : all_driver, 'lstSender' : all_inform[0], 'CurrentPage' : current_page, 'paginationPage' : execute_database[0], 'lstReceiver' : all_inform[1], 'lstType' : all_inform[2], 'len_all_order' : len_all_order}
    context_return['range_pagination_page'] = [iteration for iteration in range(1, execute_database[0] + 1)]

    if notificationMsg:
        context_return['notificationMsg'] = notificationMsg

    return render(request, 'DS/order_in_pending.html', context_return)            

def order_need_delivery(request ,current_page = 1):
    id_ds = request.session.get('id_role_user_ddelivery', None)
    
    execute_database = exec_data.get_order_need_delivery(id_ds, current_page)

    allOrderNeedDelivery = execute_database[1]
    allDriverName = execute_database[2]
    lstDriverFull = execute_database[3]
    len_all_order = execute_database[4]

    all_inform = get_inform_order.get_information(allOrderNeedDelivery)

    # dictCountryShippingAddr = countTimeExits.countTimeExitsShippingAddr(all_inform[0])
    # dictCountryDeliveryAddr = countTimeExits.countTimeExitsDeliveryAddr(all_inform[1])
    # sumMoneyOrder = countTimeExits.sumMoneyAllOrder(allOrderNeedDelivery)
    # dictDriverTimes = countTimeExits.countTimeExitsDriver(lstDriverFull)

    #sumMoneyOrder = sumMoneyOrder,dictCountryShippingAddr = dictCountryShippingAddr, dictCountryDeliveryAddr = dictCountryDeliveryAddr, dictDriverTimes = dictDriverTimes
    context_return = {'allOrderNeedDelivery' : allOrderNeedDelivery, 'allDriverName' : allDriverName, 'lstSender' : all_inform[0], 'lstReceiver' : all_inform[1], 'lstProduct' : all_inform[2], 'paginationPage' : execute_database[0], 'CurrentPage' : current_page, 'len_all_order' : len_all_order}
    context_return['range_pagination_page'] = [iteration for iteration in range(1, execute_database[0] + 1)]

    return render(request, 'DS/order_need_delivery.html', context_return)

# Log out
def log_out(request):
    request.session.clear()
    return redirect('homepage_app:Homepage_homepage')

# This route use for static for all order
def get_static(request):
    id_ds = request.session.get('id_role_user_ddelivery', None)
    allDriverDS = exec_data.get_all_driver(id_ds)

    if request.method == 'POST':
        form_data = request.POST
        
        # TODO core more here
        if 'staticForEachDriver' in form_data:
            idDriver = request.POST.get('chooseIDDriver', None).split(',')[0]
            driverName = request.POST.get('chooseIDDriver', None).split(',')[1]
            dateSearch = request.POST.get('chooseDateForEachDriver', None)
            if dateSearch == '':
                return redirect('DS_app:DS_static_order_by_driver', CurrentPage = 1, dateSearch = 'None', idDriver = idDriver,driver_name = driverName)
            else:
                return redirect('DS_app:DS_static_order_by_driver', CurrentPage = 1, dateSearch = dateSearch, idDriver = idDriver, driver_name = driverName)
        elif 'staticByDate' in form_data:
            chooseDateForStatic = request.POST.get('chooseDateForStatic', None)
            return redirect('DS_app:DS_static_by_date', CurrentPage = 1, dateValue = chooseDateForStatic)
        elif 'staticByMonth' in form_data:
            chooseMonthForStatic = request.POST.get('chooseMonthStaticMonth', None)
            return redirect('DS_app:DS_static_by_month', CurrentPage = 1, monthValue = chooseMonthForStatic)
        elif 'staticByYear' in form_data:

DS/templates/DS/DSEditOrder.html
{% extends 'baseDeliverySystem.html' %}

{% block contentPageDeliverySystem %}
    <link rel="stylesheet" href="{{url_for('DSProfileBp.static', filename = 'css/DSEditOrder.css')}}">
    {% if msg_notification is defined %}
        {% if msg_notification != 'None' %}
            {{msg_notification}}
        {% endif %}
    {% endif %}
    <div class="ds__edit__order__form">
        <form method ='post' class="input__form__tel__sender__receiver">
            <div class="input__tel__number__sender__form">
                <label>Input Telephone Number Sender</label>
                <input name="inputTelSender" type="tel" required>
            </div>
            <div>
                <label>Input Telephone Number Receiver</label>
                <input name="inputTelRecv" type="tel" required>
            </div>
            <input type="submit" name = 'submitTelNum' id="submit__tel__num__form" required>
        </form>
        <form method="post">
            <label>Input Order Number : </label>
            <input type="text" name="inputOrderNumber" required>
            <input type="submit" name="submitOrderNumber" required>
        </form>
    </div>
    {% if all_order is defined %}
        <a href="{{url_for('.dsShowAllOrderByTel', all_order = all_order, CurrentPage = 1)}}">Watch all order match</a>
    {% endif %}
    {% if edit_order == True %}
    {% if order_number_need_edit is defined %}
        <p>Edit order {{order_number_need_edit}}</p>
    {% endif %}
        <div class="edit__order__div">
            <form method="post">
                <div>
                    <div>
                        <label>Input Telephone Number Sender</label>
                        <input type="text" name="editTelSender" required>
                    </div>
                    <div>
                        <label>Input Telephone Number Receiver</label>
                        <input type="text" name="editTelReceiver" required>
                    </div>
                </div>
                <div>
                    <div>
                        <label>Input Name Sender</label>
                        <input type='text' name="editNameSender" required>
                    </div>
                    <div>
                        <label>Input Name Receiver</label>
                        <input type='text' name="editNameReceiver" required>
                    </div>
                </div>
                <input type="text" value="{{order_number_need_edit}}" name="valueCodeOrderNumber" hidden>
                <input type="submit" name="submitEditOrder" required>
            </form>
        </div>
    {% endif %}
{% endblock %}

DS/templates/DS/order_success.html
{% extends 'DS/base_ds.html' %}
{% load static %}
{% load custom_filters_ds %}

{% block contentPageDeliverySystem %}
    <script>
        var CurrentPage = parseInt('{{CurrentPage}}')
        var paginationPage = parseInt('{{paginationPage}}')
        document.onreadystatechange = function(){
            if (document.readyState === 'interactive') {
                onPageLoadPagination();

                let all_total_money = document.getElementsByClassName('total__money__order')

                for (let index = 0; index < all_total_money.length; index++){
                    let each_total_money = parseInt(all_total_money[index].innerText, 10)
                    all_total_money[index].innerText = each_total_money.toLocaleString('en-US')
                }s
            }
        } 
    </script>
    <link rel="stylesheet" href="{% static 'DS/css/order_delivery_success.css' %}">
    <script src="{% static 'DS/javascript/order_status.js' %}"></script>
    <div class="order__success__title">
        <p>{{len_all_order }} order success</p>
    </div>
    <br>
    <table>
        <tr>
            <th>No</th>
            <th>Code</th>
            <th>Sender</th>
            <th>Receiver</th>
            <th>Product Name</th>
            <th>Status</th>
            <th>Total Cost</th>
            <th>Note</th>
            <th>Driver</th>
            <th>Image Success</th>
        </tr>
        {% for index in allOrderSuccess %}
            <tr>
                <td>{{foorloop.counter}}</td>
                <td><div class="show__code__order" data-content="{{index.code_order_delivery}}">
                <a href="#">{{index.code_order_delivery}}</a></div></td>
                <td>
                    {% for sender in lstSender|get_list_item:forloop.counter0 %}
                        <p>Name : <span>{{sender.name}}</span></p>
                        <p>Telephone number : <span>{{sender.tel_num}}</span></p>
                        <p>Address : <span>{{sender.ward}}, {{sender.district}}, {{sender.province}}</span></p>
                    {% endfor %}
                </td>
                <td>
                    {% for receiver in lstReceiver|get_list_item:forloop.counter0 %}
                        <p>Name : <span>{{receiver.name}}</span></p>
                        <p>Telephone number : <span>{{receiver.tel_num}}</span></p>
                        <p>Address : <span>{{receiver.ward}}, {{receiver.district}}, {{receiver.province}}</span></p>
                    {% endfor %}
                </td>
                <td>
                    {% for product in lstType|get_list_item:forloop.counter0 %}
                        <p>Product {{forloop.counter}} : {{product.name_product}}</p>
                    {% endfor %}
                </td>
                <td>{{index.status_order}}</td>
                <td class="total__money__order">{{index.total_cost}}</td>
                <td>{{index.note}}</td>
                <td>
                    {% for driver in lstDriver|get_list_item:forloop.counter0 %}
                        {{driver.full_name_driver}}
                    {% endfor %}
                </td>
                <td>
                    <a href="#">Watch Image</a>
                </td>
            </tr>
        {% endfor %}
    </table><br>
    {% comment  %}
    <table>
        <tr>
            <th>Total Cost</th>
            <th>Total Money</th>
            <th>Driver</th>
            <th>Shipping Address</th>
            <th>Delivery Address</th>
        </tr>
        <tr>
            <td>{{allOrderSuccess|length}}</td>
            <td>{{sumMoneyOrder}}</td>
            <td>
                {% for driver in dictDriverTimes %}
                    <p>{{driver}} : {{dictDriverTimes[driver]}} order</p>
                {% endfor %}
            </td>
            <td>
                {% for index in dictCountryShippingAddr %}
                    <p>{{index}} : {{dictCountryShippingAddr[index]}} order</p>
                {% endfor %}
            </td>
            <td>
                {% for index in dictCountryDeliveryAddr %}
                    <p>{{index}} : {{dictCountryDeliveryAddr[index]}} order</p>
                {% endfor %}
            </td>
        </tr>
    </table> {% endcomment %}

    <div class="pagination__page">
        {% if paginationPage > 5%}
            <button id="btn__first__pagination__page" onclick="firstPagePagination()">Go to page 1</button>
            <button id='btn__previous__pagination' onclick="previousBtnPagination()">Previous</button>
            {% for page in range_pagination_page %}
                {% if CurrentPage == page %}
                    <a href="{% url 'DS_app:DS_order_success' page %}">
                        <button id="btn__page__pagination__page{{page}}" class="btn__pagination active__btn__pagination">{{page}}</button>
                    </a>
                {% else %}
                    <a href="{% url 'DS_app:DS_order_success' page %}">
                        <button id="btn__page__pagination__page{{page}}" class="btn__pagination">{{page}}</button>
                    </a>
                {% endif %}
            {% endfor %}
            <button id="btn__next__pagination" onclick="nextBtnPagination()">Next</button>
            <button id="btn__end__pagination__page" onclick="lastPagePagination()">Go to page end</button>
        {% else %}
            {% for page in range_pagination_page %}
                {% if CurrentPage == page %}
                    <a href="{% url 'DS_app:DS_order_success' page %}">
                        <button id="btn__page__pagination__page{{page}}" class="btn__pagination active__btn__pagination">{{page}}</button>
                    </a>
                {% else%}
                    <a href="{% url 'DS_app:DS_order_success' page %}">
                        <button id="btn__page__pagination__page{{page}}" class="btn__pagination">{{page}}</button>
                    </a>
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}

DS/templates/DS/total_money_static.html
{% extends 'DS/base_ds.html' %}
{% load static %}
{% load custom_filters_ds %}

{% block contentPageDeliverySystem %}
    <script>
        var CurrentPage = parseInt('{{CurrentPage}}')
        var paginationPage = parseInt('{{paginationPage}}')
        document.onreadystatechange = function(){
            if (document.readyState === 'interactive') {
                onPageLoadPagination();
                let all_total_money = document.getElementsByClassName('total__money__order')

                for (let index = 0; index < all_total_money.length; index++){
                    let each_total_money = parseInt(all_total_money[index].innerText, 10)
                    all_total_money[index].innerText = each_total_money.toLocaleString('en-US')
                }
            }
        } 
    </script>
    <link rel="stylesheet" href="{% static 'DS/css/static_ds.css' %}">
    <script src="{% static 'DS/javascript/static_ds.js' %}"></script>
    <div class="show__total__money">
        {% if total_money == 0 %}
            <p>Chưa có thu nhập</p>
        {% else %}
            {% if monthValue %}
                <p>Tổng tiền tháng {{monthValue}} là : {{total_money}} vnđ</p>
            {% elif dayValue %}
                <p>Tổng tiền ngày {{dayValue}} là : {{total_money}} vnđ</p>
            {% elif yearValue %}
                <p>Tổng tiền năm {{yearValue}} là : {{total_money}} vnđ</p>
            {% endif %}
        {% endif %}
    </div>
    <br>
    {% if all_order|length == 0 %}
        <p id="not__found__any__order">Not found any order</p>
    {% else %}
        <table>
            <tr>
                <th>No</th>
                <th>Code</th>
                <th>Sender</th>
                <th>Receiver</th>
                <th>Product Name</th>
                <th>Status</th>
                <th>Total Cost</th>
                <th>Note</th>
                <th>Driver</th>
                <th>Image Success</th>
            </tr>
            {% for index in all_order %}
                <tr>
                    <td>{{foorloop.counter}}</td>
                    <td><div class="show__code__order" data-content="{{index.code_order_delivery}}">
                        <a href="#">{{index.code_order_delivery}}</a></div></td>
                    <td>
                        {% for sender in lstSender|get_list_item:forloop.counter0 %}
                            <p>Name : <span>{{sender.name}}</span></p>
                            <p>Telephone number : <span>{{sender.tel_num}}</span></p>
                            <p>Address : <span>{{sender.ward}}, {{sender.district}}, {{sender.province}}</span></p>
                        {% endfor %}
                    </td>
                    <td>
                        {% for receiver in lstReceiver|get_list_item:forloop.counter0 %}
                            <p>Name : <span>{{receiver.name}}</span></p>
                            <p>Telephone number : <span>{{receiver.tel_num}}</span></p>
                            <p>Address : <span>{{receiver.ward}}, {{receiver.district}}, {{receiver.province}}</span></p>
                        {% endfor %}
                    </td>
                    <td>
                        {% for product in lstProduct|get_list_item:forloop.counter0 %}
                            <p>Product {{forloop.counter}} : {{product.name_product}}</p>
                        {% endfor %}
                    </td>
                    <td>{{index.status_order}}</td>
                    <td class="total__money__order">{{index.total_cost}}</td>
                    <td>{{index.note}}</td>
                    <td>
                        {% for driver in lstDriver|get_list_item:forloop.counter0 %}
                            {{driver}}
                        {% endfor %}
                    </td>
                    <td>
                        <a href="#">Watch Image</a>
                    </td>
                </tr>
            {% endfor %}
        </table>
    {% endif %}
    
    <div class="pagination__page">
        {% if paginationPage > 5%}
            <button id="btn__first__pagination__page" onclick="firstPagePagination()">Go to page 1</button>
            <button id='btn__previous__pagination' onclick="previousBtnPagination()">Previous</button>
            {% for page in range_pagination_page %}
                {% if CurrentPage == page %}
                    {% if monthValue %}
                        <a href="{% url 'DS_app:DS_total_money_one_month' monthValue page %}">
                            <button id="btn__page__pagination__page{{page}}" class="btn__pagination active__btn__pagination">{{page}}</button>
                        </a>
                    {% elif dayValue %}
                        <a href="{% url 'DS_app:DS_total_money_one_day' dayValue page %}">
                            <button id="btn__page__pagination__page{{page}}" class="btn__pagination active__btn__pagination">{{page}}</button>
                        </a>
                    {% elif yearValue %}
                        <a href="{% url 'DS_app:DS_total_money_one_year' yearValue page %}">
                            <button id="btn__page__pagination__page{{page}}" class="btn__pagination active__btn__pagination">{{page}}</button>
                        </a>
                    {% endif %}
                {% else %}
                    {% if monthValue %}
                        <a href="{% url 'DS_app:DS_total_money_one_month' monthValue page %}">
                            <button id="btn__page__pagination__page{{page}}" class="btn__pagination">{{page}}</button>
                        </a>
                    {% elif dayValue %}
                        <a href="{% url 'DS_app:DS_total_money_one_day' dayValue page %}">
                            <button id="btn__page__pagination__page{{page}}" class="btn__pagination">{{page}}</button>
                        </a>
                    {% elif yearValue %}
                        <a href="{% url 'DS_app:DS_total_money_one_year' yearValue page %}">
                            <button id="btn__page__pagination__page{{page}}" class="btn__pagination">{{page}}</button>
                        </a>
                    {% endif %}
                {% endif %}
            {% endfor %}
            <button id="btn__next__pagination" onclick="nextBtnPagination()">Next</button>
            <button id="btn__end__pagination__page" onclick="lastPagePagination()">Go to page end</button>
        {% else %}
            {% for page in range_pagination_page %}
                {% if CurrentPage == page %}
                    {% if monthValue %}
                        <a href="{% url 'DS_app:DS_total_money_one_month' monthValue page %}">
                            <button id="btn__page__pagination__page{{page}}" class="btn__pagination active__btn__pagination">{{page}}</button>
                        </a>
                    {% elif dayValue %}
                        <a href="{% url 'DS_app:DS_total_money_one_day' dayValue page %}">
                            <button id="btn__page__pagination__page{{page}}" class="btn__pagination active__btn__pagination">{{page}}</button>
                        </a>
                    {% elif yearValue %}
                        <a href="{% url 'DS_app:DS_total_money_one_year' yearValue page %}">
                            <button id="btn__page__pagination__page{{page}}" class="btn__pagination active__btn__pagination">{{page}}</button>
                        </a>
                    {% endif %}
                {% else%}
                    {% if monthValue %}
                        <a href="{% url 'DS_app:DS_total_money_one_month' monthValue page %}">
                            <button id="btn__page__pagination__page{{page}}" class="btn__pagination">{{page}}</button>
                        </a>
                    {% elif dayValue %}
                        <a href="{% url 'DS_app:DS_total_money_one_day' dayValue page %}">
                            <button id="btn__page__pagination__page{{page}}" class="btn__pagination">{{page}}</button>
                        </a>
                    {% elif yearValue %}
                        <a href="{% url 'DS_app:DS_total_money_one_year' yearValue page %}">
                            <button id="btn__page__pagination__page{{page}}" class="btn__pagination">{{page}}</button>
                        </a>
                    {% endif %}
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}