DDelivery/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('homepage/', include('Homepage.urls')),
    path('users/', include('Users.urls')),
    path('delivery-system/', include('DS.urls')),
    path('driver/', include('Driver.urls')),
    path('gen-pdf/', include('GPDF.urls')),
    path('gen-xlsx/', include('GXLSX.urls'))
]

DS/urls.py
from django.urls import path

from . import views
from . import profile_view

app_name = 'DS_app'

urlpatterns = [
    path('homepage/', views.base_DS_page, name = 'DS_homepage'),
    path('order-in-delivery/<int:current_page>/', views.order_delivery, name = 'DS_order_in_delivery'),
    path('order-successful/<int:current_page>/', views.order_success, name = 'DS_order_success'),
    path('order-in-pending/<int:current_page>/<str:notificationMsg>/', views.order_in_pending, name = 'DS_order_pending'),
    path('order-need-delivery/<int:current_page>/', views.order_need_delivery, name = 'DS_order_need_delivery'),
    path('log-out/', views.log_out, name = 'DS_log_out'),
    path('static/', views.get_static, name = 'DS_get_static'),
    path('static-order-by-driver/<dateSearch>/<idDriver>/<CurrentPage>/<driver_name>/', views.get_static_ds_driver, name = 'DS_static_order_by_driver'),
    path('static-by-date/<int:CurrentPage>/<dateValue>/', views.get_static_ds_date, name = 'DS_static_by_date'),
    path('static-by-month/<int:CurrentPage>/<monthValue>/', views.get_static_month, name = 'DS_static_by_month'),
    path('static-by-year/<int:CurrentPage>/<yearValue>/', views.get_static_year, name = 'DS_static_by_year'),
    path('static-total-money-one-month/<monthValue>/<int:CurrentPage>/', views.total_money_one_month, name = 'DS_total_money_one_month'),
    path('static-total-money-one-day/<dayValue>/<int:CurrentPage>/', views.total_money_one_day, name = 'DS_total_money_one_day'),
    path('static-total-money-one-year/<yearValue>/<int:CurrentPage>/', views.total_money_one_year, name = 'DS_total_money_one_year'),
    path('search-order/', views.search_order, name = 'DS_search_order'),
    path('search-by-code-order/<int:CurrentPage>/<CodeOrder>/<msgNotification>/', views.searchOrderByCodeOrder, name = 'DS_search_order_by_code'),
    path('search-by-day/<int:CurrentPage>/<chooseDate>/', views.searchOrderDSByDay, name = 'DS_search_order_by_day'),
    path('search-by-month/<int:CurrentPage>/<chooseMonth>/', views.searchOrderDSByMonth, name = 'DS_search_order_by_month'),
    path('search-by-year/<int:CurrentPage>/<chooseYear>/', views.searchOrderDSByYear, name = 'DS_search_order_by_year'),
    path('search-by-tel/<telSender>/<telReceiver>/<int:CurrentPage>/', views.searchOrderDSByTel, name = 'DS_search_order_by_tel'),
    path('search-order-all/<int:CurrentPage>/', views.searchOrderDSAll, name = 'DS_search_order_all'),
    path('order-return/<int:CurrentPage>/', views.orderReturnDS, name = 'DS_order_return'),
    path('profile/homepage/', views.baseDSProfile, name ='DS_base_profile'),
]

Driver/urls.py
from django.urls import path

from . import views 
from . import profile_views

app_name = 'Driver_app'

urlpatterns = [
    path('homepage/', views.baseDriverPage, name = 'Driver_homepage'),
    path('order-was-successful/<int:CurrentPage>/', views.orderSuccess, name = 'Driver_order_success'),
    path('order-delivery/<int:CurrentPage>/<notificationMsg>', views.orderDelivery, name = 'Driver_order_delivery'),
    path('order-need-delivery/<int:CurrentPage>/<notificationMsg>', views.orderNeedTransmit, name = 'Driver_order_need_delivery'),
    path('log-out/', views.logoutDriver, name = 'Driver_log_out'),
    path('update-all-delivery-order', views.updateStatusDelivery, name = 'Driver_update_all_delivery_order'),
    path('order-return/<int:CurrentPage>/', views.orderReturnDriver, name = 'Driver_order_return'),
    path('profile/<notificationMsg>', profile_views.baseDriverPersonalPage, name = 'Driver_profile')
]

Driver/models.py
from django.db import models

# Create your models here.

Driver/views.py
from django.shortcuts import render
import datetime
from firebase_admin import storage
from dotenv import load_dotenv
import jwt
import platform
import os

from . import exec_data
from . import get_inform_order

# Create your views here.

# TODO
# This function use for upload image to firebase storage
# When driver choose image and press submit button, this function will execute
# def uploadImageFirebase(files, remote_file_name):
#     bucket = storage.bucket()
#     blob = bucket.blob(remote_file_name)
#     blob.upload_from_file(files.stream)

# TODO
# Check valid token and exp time, if not return homepage or login page
# @driverPage_blueprint.before_request
# def checkCurrentToken():
#     if 'tokenDeliveryWedDemo' not in session:
#         return redirect(url_for('loginAccountBp.loginAccount'))

#     # This function help load a key - value in .env file
#     load_dotenv()
#     secretKey = os.getenv('secret_key')
#     decodeToken = jwt.decode(session['tokenDeliveryWedDemo'], secretKey, algorithms = ["HS256"])

#     currentTime = datetime.datetime.now()
#     endTimeToken = datetime.datetime.strptime(decodeToken['endTimeTokenStr'], f'%d-%m-%Y %H:%M:%S')

#     # Check exp time, if end exp time, return to login page
#     if currentTime < endTimeToken:
#         roleUserTemp = decodeToken['roleUser']
#         if roleUserTemp == 'Driver':
#             session['roleUser'] = 'Driver'
#             session['idDriver'] = decodeToken['idRoleUser']
#         else:
#             return "<p>You are not login at role user, so you can't access this page</p>"
#     else:
#         return redirect(url_for('loginAccountBp.loginAccount', notificationEndToken = True))


def baseDriverPage(request):
    id_driver =  request.session.get('id_role_user_ddelivery', None)

    execute_database = exec_data.driverBasePage(id_driver)
    driverName = execute_database[0]
    len_all_order = execute_database[1] 

    context_return = {'driverName' : driverName, 'allOrderNeedDeliveryHomepage' : len_all_order}
    return render(request, 'Driver/baseDriverPage.html', context_return)

def orderSuccess(request, CurrentPage = 1):
    if request.method == 'POST':
        form_data = request.POST
        
        # TODO code here
        # if 'inputFilterDate' in form_data:
        #     dateValue = form_data['inputDateFilter']
        #     return redirect(url_for('orderSuccessFilterBp.orderSuccessFilterDate', CurrentPage = 1, dateValue = dateValue))     
        # elif 'inputFilterMonth' in form_data:
        #     monthValue = form_data['inputMonthFilter']
        #     return redirect(url_for('orderSuccessFilterBp.orderSuccessFilterMonth', CurrentPage = 1, monthValue = monthValue))
        # elif 'inputFilterYear' in form_data:
        #     yearValue = form_data['inputYearFilter']
        #     return redirect(url_for('orderSuccessFilterBp.orderSuccessFilterYear', CurrentPage = 1, yearValue = yearValue))
            
    id_driver = request.session.get('id_role_user_ddelivery', None)
    execute_database = exec_data.driverOrderSuccess(id_driver, CurrentPage)
    allOrderSuccess = execute_database[1]
    paginationPage = execute_database[0]
    len_lst_order_success = execute_database[2]

    all_inform = get_inform_order.get_information(allOrderSuccess)

    context_return = {'allOrderSuccess' : allOrderSuccess, 'lstSender' : all_inform[0], 'lstReceiver' : all_inform[1], 'lstType' : all_inform[2], 'CurrentPage' : CurrentPage, 'paginationPage': paginationPage, 'len_lst_order_success' : len_lst_order_success}
    context_return['range_pagination_page'] = [iteration for iteration in range(1, paginationPage + 1)]

    return render(request, 'Driver/orderSuccess.html', context_return)

def orderDelivery(request, CurrentPage = 1, notificationMsg = None):
    if request.method == 'POST':
        getCodeOrder = request.POST.get('valueDeliverySuccess', None)
        exec_data.driverPostOrderDelivery(getCodeOrder)
        
        # TODO : code here
        # imageDeliverySuccess = request.files['ImageDeliverySuccess']
        # uploadImageFirebase(imageDeliverySuccess, f'DeliverySuccess/{getCodeOrder}.jpg')

        return redirect('Driver_app:Driver_order_delivery', CurrentPage = 1, notificationMsg = f'Update Success order "{getCodeOrder}"')
    
    id_driver = request.session.get('id_role_user_ddelivery', None)

    execute_database = exec_data.driverOrderDelivery(id_driver, CurrentPage)
    lstOrder = execute_database[1]
    paginationPage = execute_database[0]
    len_lst_order = execute_database[2]

    all_inform = get_inform_order.get_information(lstOrder)
    context_return = {'allOrderDelivery' : lstOrder, 'lstSender' : all_inform[0],
        'lstReceiver' : all_inform[1], 'CurrentPage' : CurrentPage,
        'lstProduct' : all_inform[2], 'paginationPage' : paginationPage, 'len_lst_order' : len_lst_order}
    context_return['range_pagination_page'] = [iteration for iteration in range(1, paginationPage + 1)]

    if notificationMsg is None:
        context_return['notificationMsg'] = None
        return render(request, 'Driver/orderDelivery.html', context_return)
    else:
        context_return['notificationMsg'] = notificationMsg
        return render(request, 'Driver/orderDelivery.html', context_return)

def orderNeedTransmit(request, CurrentPage = 1, notificationMsg = None):
    id_driver = request.session.get('id_role_user_ddelivery', None)
    if request.method == 'POST':
        if 'updateTransmit' in request.POST:
            getCodeOrder = request.POST.get('valueTransmit', None)
            
            # TODO : code here
            # imageGetProduct = request.files['ImageGetProduct']
            # imageInTransport = request.files['ImageInTransport']
            # uploadImageFirebase(imageGetProduct, f'ImageGetProduct/{getCodeOrder}.jpg')
            # uploadImageFirebase(imageInTransport, f'ImageInTransport/{getCodeOrder}.jpg')
            
            exec_data.driverPostOrderNeedDelivery(getCodeOrder)
            return redirect('Driver_app:Driver_order_need_delivery', CurrentPage = 1, notificationMsg = f'Update Delivery order {getCodeOrder} Success')

    execute_database = exec_data.driverOrderNeedDelivery(id_driver, CurrentPage)
    lstOrder = execute_database[1]
    paginationPage = execute_database[0]
    nameDriver = execute_database[2]
    len_lst_order = execute_database[3]

    all_inform = get_inform_order.get_information(lstOrder)

    context_return = {'allOrderNeedDelivery' : lstOrder, 'lstSender' : all_inform[0], 'lstReceiver' : all_inform[1],
        'lstProduct' : all_inform[2], 'nameDriver' : nameDriver, 'CurrentPage' : CurrentPage, 'paginationPage' : paginationPage,
        'len_lst_order' : len_lst_order}
    context_return['range_pagination_page'] = [iteration for iteration in range(1, paginationPage + 1)]

    if notificationMsg is None:
        context_return['notificationMsg'] = None 
        return render(request, 'Driver/orderNeedTransmit.html', context_return)
    else:
        context_return['notificationMsg'] = notificationMsg
        return render(request, 'Driver/orderNeedTransmit.html', context_return)

def logoutDriver(request):
    request.session.clear()
    return redirect('homepage_app:Homepage_homepage')

def updateStatusDelivery(request):
    id_driver = request.session.get('id_role_user_ddelivery', None)

    exec_data.driverUpdateStatusDelivery(id_driver)
    return redirect('Driver_app:Driver_order_need_delivery',CurrentPage = 1)

def orderReturnDriver(request, CurrentPage = 1):
    id_driver = request.session.get('id_role_user_ddelivery', None)

    execute_database = exec_data.returnOrderDriver(id_driver, CurrentPage)
    all_order = execute_database['all_order']
    paginationPage = execute_database['pagination']
    len_all_order = execute_database['len_all_order']

    all_inform = get_inform_order.get_information(all_order)

    return_para = {'lstSender' : all_inform[0], 'lstReceiver' : all_inform[1], 'lstProduct' : all_inform[2], 'paginationPage' : paginationPage, 'CurrentPage' : CurrentPage,
        'len_all_order' : len_all_order, 'all_order' : all_order}
    return_para['range_pagination_page'] = [iteration for iteration in range(1, paginationPage + 1)]

    return render(request, 'Driver/orderReturnDriver.html', return_para)

Driver/templates/Driver/autoUpdateRoute.html
{% extends 'baseDriverPage.html' %}

{% block baseDriverHomepage %}
{% endblock %}

{% block functionDriverPage %}
    <link rel="stylesheet" href=" {{ url_for('autoUpdateRouteBp.static', filename = 'css/autoUpdateRoute.css')}}">
    <table>
        <tr>
            <th>Step</th>
            <th>From:</th>
            <th>To:</th>
        </tr>
        {% for index in range(0, shortestRouteStr|length) %}
            {% if index == 0 %}
                <tr>
                    <td>{{loop.index}}</td>
                    <td>Store</td>
                    <td>{{shortestRouteStr[index]}}</td>
                </tr>
            {% elif index == (shortestRouteStr|length - 1) %}
                <tr>
                    <td>{{loop.index}}</td>
                    <td>{{shortestRouteStr[index]}}</td>
                    <td>Store</td>
                </tr>
            {% else %}
                <tr>
                    <td>{{loop.index}}</td>
                    <td>{{shortestRouteStr[index - 1]}}</td>
                    <td>{{shortestRouteStr[index]}}</td>
                </tr>
            {% endif %}
        {% endfor %}
    </table>
    <br>

    <div class="link__option">
        <a href=" {{ url_for('driverPage.orderNeedTransmit', CurrentPage = 1) }} ">Comeback to previous page</a>
        <a href=" {{ url_for('driverPage.updateStatusDelivery') }} ">Delivery All Order Need Delivery</a>
        <form method="post">
            <input type="submit" name="seeMap" value = 'See maps' required>
        </form>
    </div>
    
{% endblock %}

Driver/templates/Driver/baseDriverPage.html
{% load static %}

<!-- Comment block -->
<link rel="stylesheet" href=" {% static 'Driver/css/baseDriverPage.css' %} ">
<script src="{% static 'Driver/javascript/baseDriverPage.js' %}"></script>
<div class="header__page">
    <header>
        <div class="logo__header">
            <a href="{% url 'Driver_app:Driver_homepage' %}" class="link__to__navigation">
                <img src="{% static 'Driver/images/Logo.png' %}" alt="logo" id="header__logo__image">
            </a>
        </div>
        <div class="header__menu">
            <div class="header__menu__language">
                <p id="header__menu__language__title">Ngôn ngữ</p>
                <div class="choose__language__header">
                    <p class="each__language__title">Việt Nam</p>
                    <p class="each__language__title">English</p>
                </div>
            </div>
            <ul class="menu__header">
                <li class="menu__header__item">
                    <a href="#" class="menu__header__title">Menu</a>
                    <div class="menu__header__child">
                        <div class="menu__header__child__item">
                            <h4>Order</h4>
                            <ul class="menu__child__list">
                                <li><a href="#" class="link__to__navigation">Need Delivery</a></li>
                                <li><a href="#" class="link__to__navigation">In Delivery</a></li>
                                <li><a href="#" class="link__to__navigation">Success</a></li>
                                <li><a href="#" class="link__to__navigation">Return</a></li>
                            </ul>
                        </div>
                        <div class="menu__header__child__item">
                            <h4>Static & Search Order</h4>
                            <ul class="menu__child__list">
                                <li><a href="#" class="link__to__navigation">Static ( Revenue )</a></li>
                                <li><a href="#" class="link__to__navigation">Search Order</a></li>
                            </ul>
                        </div>
                    </div>
                </li>
                <li>
                    <a href="#" class="link__to__navigation log__out__menu">Log out</a>
                </li>
            </ul>
        </div>

    </header>
</div>
<!-- End of comment block -->
{% block baseDriverHomepage %}
    <div class="content__homepage__driver">
        {% if driverName %}
            <div class="content__homepage__driver__left">
                <h1>Hello driver {{driverName}}</h1><br>
                <p>You have {{allOrderNeedDeliveryHomepage}} order need-delivery. Delivery now
                    <a id="homepage__driver__link__order__need__transmit" href="#">Order Need Delivery</a>
                </p>
            </div>
        {% endif %}
        <img id="image__homepage__driver" src="{% static 'Driver/images/ImageHompageDriver.png' %}">
    </div>
{% endblock %}
{% block functionDriverPage %}
{% endblock %}
<footer>
    <div class="footer__inner">
        <div class="footer__item">
            <h3>Order</h3>
            <a href="#" class="footer_link">Need Delivery</a>
            <a href="#" class="footer_link">In Delivery</a>
            <a href="#" class="footer_link">Success</a>
            <a href="#" class="footer_link">Return</a>
        </div>
        <div class="footer__item">
            <h3>Static</h3>
            <a href="#" class="footer_link">Static ( Revenue )</a>
        </div>
        <div class="footer__item">
            <h3>Search Order</h3>
            <a href="#" class="footer_link">Search Order</a>
        </div>
        <div class="footer__item">
            <img src="{% static 'Driver/images/Logo.png' %}" alt="logo" id="footer__logo__image">
            <p class="footer__inform__company">Address : Hồ Chí Minh City</p>
            <p class="footer__inform__company">Tel : 123456789</p>
        </div>
    </div>
</footer>

Driver/templates/Driver/orderReturnDriver.html
{% extends 'Driver/baseDriverPage.html' %}
{% load static %}
{% load custom_filters_driver %}

{% block baseDriverHomepage %}
{% endblock %}

{% block functionDriverPage %}
    <link rel="stylesheet" href="{% static 'Driver/css/orderReturnDriver.css' %}">
    <script src="{% static 'Driver/javascript/orderDelivery.js' %}"></script>
    <script>
        var CurrentPage = parseInt('{{CurrentPage}}')
        var paginationPage = parseInt('{{paginationPage}}')
        document.onreadystatechange = function(){
            if (document.readyState === 'interactive') {
                onPageLoadPagination();
                let all_total_money = document.getElementsByClassName('total__money__order')

                for (let index = 0; index < all_total_money.length; index++){
                    let each_total_money = parseInt(all_total_money[index].innerText, 10)
                    all_total_money[index].innerText = each_total_money.toLocaleString('en-US')
                }
            }
        } 
    </script>

    <div class="title__content__page">
        <p>Found {{len_all_order}} order return.</p>
    </div>
    {% if all_order|length == 0 %}
        <p>Not found nay order</p>
    {% else %}
        <table>
            <tr>
                <th>No.</th>
                <th>Code</th>
                <th>Sender</th>
                <th>Receiver</th>
                <th>Name Product</th>
                <th>Status</th>
                <th>Total cost</th>
                <th>Note</th>
                <th>Date Create</th>
                <th>Image Get Product</th>
                <th>Image In Delivery</th>
            </tr>
            {% for index in all_order %}
                <tr>
                    <td>{{foorloop.counter}}</td>
                    <td><div class="show__code__order" data-content="{{index.code_order_delivery}}">
                    <a href="#">{{index.code_order_delivery}}</a></div></td>
                    <td>
                        {% for sender in lstSender|get_list_item:forloop.counter0 %}
                            <p>Name : <span>{{sender.name}}</span></p>
                            <p>Telephone number : <span>{{sender.tel_num}}</span></p>
                            <p>Address : <span>{{sender.ward}}, {{sender.district}}, {{sender.province}}</span></p>
                        {% endfor %}
                    </td>
                    <td>
                        {% for receiver in lstReceiver|get_list_item:forloop.counter0 %}
                            <p>Name : <span>{{receiver.name}}</span></p>
                            <p>Telephone number : <span>{{receiver.tel_num}}</span></p>
                            <p>Address : <span>{{receiver.ward}}, {{receiver.district}}, {{receiver.province}}</span></p>
                        {% endfor %}
                    </td>
                    <td>
                        {% for product in lstType|get_list_item:forloop.counter0 %}
                            <p>Product {{forloop.counter}} : {{product.name_product}}</p>
                        {% endfor %}
                    </td>
                    <td>{{index.status_order}}</td>
                    <td class="total__money__order">{{index.total_cost}}</td>
                    <td>{{index.note}}</td>
                    <td>{{index.date_create}}</td>
                    <td>
                        <a href="#">Watch Image</a>
                    </td>
                    <td>
                        <a href="#">Watch Image</a>
                    </td>
                </tr>
            {% endfor %}
        </table>
        <div class="pagination__page">
            {% if paginationPage > 5%}
                <button id="btn__first__pagination__page" onclick="firstPagePagination()">Go to page 1</button>
                <button id='btn__previous__pagination' onclick="previousBtnPagination()">Previous</button>
                {% for page in range_pagination_page %}
                    {% if CurrentPage == page %}
                        <a href="{% url 'Driver_app:Driver_order_return' page %}">
                            <button id="btn__page__pagination__page{{page}}" class="btn__pagination active__btn__pagination">{{page}}</button>
                        </a>
                    {% else %}
                        <a href="{% url 'Driver_app:Driver_order_return' page %}">
                            <button id="btn__page__pagination__page{{page}}" class="btn__pagination">{{page}}</button>
                        </a>
                    {% endif %}
                {% endfor %}
                <button id="btn__next__pagination" onclick="nextBtnPagination()">Next</button>
                <button id="btn__end__pagination__page" onclick="lastPagePagination()">Go to page end</button>
            {% else %}
                {% for page in range_pagination_page %}
                    {% if CurrentPage == page %}
                        <a href="{% url 'Driver_app:Driver_order_return' page %}">
                            <button id="btn__page__pagination__page{{page}}" class="btn__pagination active__btn__pagination">{{page}}</button>
                        </a>
                    {% else%}
                        <a href="{% url 'Driver_app:Driver_order_return' page %}">
                            <button id="btn__page__pagination__page{{page}}" class="btn__pagination">{{page}}</button>
                        </a>
                    {% endif %}
                {% endfor %}
            {% endif %}
        </div>
    {% endif %}
{% endblock %}

Driver/templates/Driver/orderSuccess.html
{% extends 'Driver/baseDriverPage.html' %}
{% load static %}
{% load custom_filters_driver %}

{% block baseDriverHomepage %}
{% endblock %}

{% block functionDriverPage %}
    <link rel="stylesheet" href="{% static 'Driver/css/orderSuccess.css' %}">
    <script src="{% static 'Driver/javascript/orderSuccess.js' %}"></script>
    
    <div class="title__option__page">
        <div>
            <p class="order__detail__each__title">{{len_lst_order_success}} Order delivery successful</p>
        </div>
        <div>
            <select id="option__filter" onchange="chooseFilter()">
                <option value="notFilter">Choose Filter</option>
                <option value="date">Filter by Day</option>
                <option value="month">Filter by month</option>
                <option value="year">Filter by year</option>
            </select>
            <form method="post" id="form__input__filter">
                {% csrf_token %}
                <input type="date" name="inputDateFilter" id="input__date__filter" class="input__filter">
                <input type="month" name="inputMonthFilter" id="input__month__filter" class="input__filter">
                <input type="number" max="2099" min="1900" placeholder="2023" name="inputYearFilter" id="input__year__filter" class="input__filter">
                <input name="inputFilterDate" type="submit" value="Find" id="input__submit__filter__date" class="input__filter">
                <input name="inputFilterMonth" type="submit" value="Find" id="input__submit__filter__month" class="input__filter">
                <input name="inputFilterYear" type="submit" value="Find" id="input__submit__filter__year" class="input__filter">
            </form>
        </div>
    </div> 
    <div class="order__finish">
        <table>
            <tr>
                <th>No.</th>
                <th>Code</th>
                <th>Sender</th>
                <th>Receiver</th>
                <th>Name Product</th>
                <th>Status</th>
                <th>Total Cost</th>
                <th>Note</th>
                <th>Date Create</th>
                <th>Image Order Success</th>
            </tr>
            {% for index in allOrderSuccess %}
                <tr>
                    <td>{{foorloop.counter}}</td>
                    <td><div class="show__code__order" data-content="{{index.code_order_delivery}}">
                    <a href="#">{{index.code_order_delivery}}</a></div></td>
                    <td>
                        {% for sender in lstSender|get_list_item:forloop.counter0 %}
                            <p>Name : <span>{{sender.name}}</span></p>
                            <p>Telephone number : <span>{{sender.tel_num}}</span></p>
                            <p>Address : <span>{{sender.ward}}, {{sender.district}}, {{sender.province}}</span></p>
                        {% endfor %}
                    </td>
                    <td>
                        {% for receiver in lstReceiver|get_list_item:forloop.counter0 %}
                            <p>Name : <span>{{receiver.name}}</span></p>
                            <p>Telephone number : <span>{{receiver.tel_num}}</span></p>
                            <p>Address : <span>{{receiver.ward}}, {{receiver.district}}, {{receiver.province}}</span></p>
                        {% endfor %}
                    </td>
                    <td>
                        {% for product in lstType|get_list_item:forloop.counter0 %}
                            <p>Product {{forloop.counter}} : {{product.name_product}}</p>
                        {% endfor %}
                    </td>
                    <td>{{index.status_order}}</td>
                    <td class="total__money__order">{{index.total_cost}}</td>
                    <td>{{index.note}}</td>
                    <td>{{index.date_create}}</td>
                    <td>
                        <a href="#">Watch Image</a>
                    </td>
                </tr>
            {% endfor %}
        </table>
        <div class="pagination__page">
            {% if paginationPage > 5%}
                <button id="btn__first__pagination__page" onclick="firstPagePagination()">Go to page 1</button>
                <button id='btn__previous__pagination' onclick="previousBtnPagination()">Previous</button>
                {% for page in range_pagination_page %}
                    {% if CurrentPage == page %}
                        <a href="{% url 'Driver_app:Driver_order_success' page %}">
                            <button id="btn__page__pagination__page{{page}}" class="btn__pagination active__btn__pagination">{{page}}</button>
                        </a>
                    {% else %}
                        <a href="{% url 'Driver_app:Driver_order_success' page %}">
                            <button id="btn__page__pagination__page{{page}}" class="btn__pagination">{{page}}</button>
                        </a>
                    {% endif %}
                {% endfor %}
                <button id="btn__next__pagination" onclick="nextBtnPagination()">Next</button>
                <button id="btn__end__pagination__page" onclick="lastPagePagination()">Go to page end</button>
            {% else %}
                {% for page in range_pagination_page %}
                    {% if CurrentPage == page %}
                        <a href="{% url 'Driver_app:Driver_order_success' page %}">
                            <button id="btn__page__pagination__page{{page}}" class="btn__pagination active__btn__pagination">{{page}}</button>
                        </a>
                    {% else%}
                        <a href="{% url 'Driver_app:Driver_order_success' page %}">
                            <button id="btn__page__pagination__page{{page}}" class="btn__pagination">{{page}}</button>
                        </a>
                    {% endif %}
                {% endfor %}
            {% endif %}
        </div>
    </div>
{% endblock %}

Driver/templates/Driver/showImageFbDriver.html
{% if imageShow is defined %}
    <img src="data:image/jpeg;base64,{{imageShow}}" alt="Image" width="500px">
{% elif errorShowImage is defined %}
    <p>{{errorShowImage}}</p>
{% else %}
    <p>Maybe, you don't give code Order success</p>
{% endif %}