DDelivery/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('homepage/', include('Homepage.urls')),
    path('users/', include('Users.urls')),
    path('delivery-system/', include('DS.urls')),
    path('driver/', include('Driver.urls')),
    path('gen-pdf/', include('GPDF.urls')),
    path('gen-xlsx/', include('GXLSX.urls'))
]

DS/urls.py
from django.urls import path

from . import views
from . import profile_view

app_name = 'DS_app'

urlpatterns = [
    path('homepage/', views.base_DS_page, name = 'DS_homepage'),
    path('order-in-delivery/<int:current_page>/', views.order_delivery, name = 'DS_order_in_delivery'),
    path('order-successful/<int:current_page>/', views.order_success, name = 'DS_order_success'),
    path('order-in-pending/<int:current_page>/<str:notificationMsg>/', views.order_in_pending, name = 'DS_order_pending'),
    path('order-need-delivery/<int:current_page>/', views.order_need_delivery, name = 'DS_order_need_delivery'),
    path('log-out/', views.log_out, name = 'DS_log_out'),
    path('static/', views.get_static, name = 'DS_get_static'),
    path('static-order-by-driver/<dateSearch>/<idDriver>/<CurrentPage>/<driver_name>/', views.get_static_ds_driver, name = 'DS_static_order_by_driver'),
    path('static-by-date/<int:CurrentPage>/<dateValue>/', views.get_static_ds_date, name = 'DS_static_by_date'),
    path('static-by-month/<int:CurrentPage>/<monthValue>/', views.get_static_month, name = 'DS_static_by_month'),
    path('static-by-year/<int:CurrentPage>/<yearValue>/', views.get_static_year, name = 'DS_static_by_year'),
    path('static-total-money-one-month/<monthValue>/<int:CurrentPage>/', views.total_money_one_month, name = 'DS_total_money_one_month'),
    path('static-total-money-one-day/<dayValue>/<int:CurrentPage>/', views.total_money_one_day, name = 'DS_total_money_one_day'),
    path('static-total-money-one-year/<yearValue>/<int:CurrentPage>/', views.total_money_one_year, name = 'DS_total_money_one_year'),
    path('search-order/', views.search_order, name = 'DS_search_order'),
    path('search-by-code-order/<int:CurrentPage>/<CodeOrder>/<msgNotification>/', views.searchOrderByCodeOrder, name = 'DS_search_order_by_code'),
    path('search-by-day/<int:CurrentPage>/<chooseDate>/', views.searchOrderDSByDay, name = 'DS_search_order_by_day'),
    path('search-by-month/<int:CurrentPage>/<chooseMonth>/', views.searchOrderDSByMonth, name = 'DS_search_order_by_month'),
    path('search-by-year/<int:CurrentPage>/<chooseYear>/', views.searchOrderDSByYear, name = 'DS_search_order_by_year'),
    path('search-by-tel/<telSender>/<telReceiver>/<int:CurrentPage>/', views.searchOrderDSByTel, name = 'DS_search_order_by_tel'),
    path('search-order-all/<int:CurrentPage>/', views.searchOrderDSAll, name = 'DS_search_order_all'),
    path('order-return/<int:CurrentPage>/', views.orderReturnDS, name = 'DS_order_return'),
    path('profile/homepage/', views.baseDSProfile, name ='DS_base_profile'),
]

Users/urls.py
from django.urls import path

from . import views 

app_name = 'Users_app'

urlpatterns = [
    path('homepage/', views.base_user_page, name='Users_base_user_page'),
    path('send-product/', views.users_send_product, name='Users_send_product_page'),
    path('user-page/get-address/get-province/', views.userGetAllProvince, name='Users_get_all_province'),
    path('user-page/get-address/get-district/', views.userGetDistrictFromProvince, name='Users_get_all_district'),
    path('user-page/get-address/get-wards/', views.userGetWardFromDistrict, name='Users_get_all_ward'),
    path('return-order/<int:current_page>', views.return_order, name='Users_return_order'),
    path('logout/', views.users_logout, name = 'Users_log_out'),
    path('search-order/', views.users_search_order, name = 'Users_search_order'),
    path('personal-profile-homepage/', views.base_personal_profile, name = 'Users_personal_profile_homepage'),
    path('show-all-order/<int:current_page>/', views.user_static_show_all_order, name = 'Users_show_all_order'),
    path('static-by-date/<int:current_page>/<date_now>/', views.user_static_order_by_date, name='Users_static_order_by_date'),
    path('static-order-success/<int:current_page>/', views.user_static_order_success, name = 'Users_static_order_success'),
    path('static-order-pending/<int:current_page>/', views.user_static_order_pending, name = 'Users_static_order_pending'),
    path('static-order-delivery/<int:current_page>/', views.user_static_order_delivery, name = 'Users_static_order_delivery'),
    path('static-order-need-delivery/<int:current_page>/', views.user_static_order_need_delivery, name = 'Users_static_order_need_delivery')
]

Users/models.py
from django.db import models

# Create your models here.

Users/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from dotenv import load_dotenv
import datetime
import os
import jwt

from . import exec_data 
from . import get_inform_order

# This function try to check token. If token already is use. It continue browsing or redirect to homepage
def check_login_required(token_str):
    if token_str == '':
        return 'empty'
    else:
        load_dotenv()
        secret_key = os.getenv('secret_key')
        decode_token = jwt.decode(token_str, secret_key, algorithms = ["HS256"])
        current_time = datetime.datetime.now()
        end_time_token = datetime.datetime.strptime(decode_token['endTimeTokenStr'], f'%d-%m-%Y %H:%M:%S')
        if current_time < end_time_token:
            role_user_temp = decode_token['roleUser']
            if role_user_temp == 'users':
                return {'role_user' : 'users', 'id_users' : decode_token['idRoleUser']}
            else:
                return 'NP'
        else:
            return 'ET'

# 3 function help to load and get division
def userGetAllProvince(request):
    get_all_province = exec_data.get_all_province()
    lst_all_province_temp = [item['province'] for item in get_all_province]
    dict_all_province = {'result' : lst_all_province_temp}
    return JsonResponse(dict_all_province)
    
def userGetDistrictFromProvince(request):
    name_province = request.POST.get('province', None)
    get_all_district = exec_data.get_all_district_by_name_province(name_province)
    lst_all_district = [item['district'] for item in get_all_district]
    dict_all_district = {'result' : lst_all_district}
    return JsonResponse(dict_all_district)

def userGetWardFromDistrict(request):
    name_province = request.POST.get('province', None)
    name_district = request.POST.get('district', None)
    get_all_ward = exec_data.get_all_ward_by_name_province_name_district(name_province, name_district)
    lst_all_ward = [item['ward'] for item in get_all_ward]
    dict_all_ward = {'result' : lst_all_ward}
    return JsonResponse(dict_all_ward)

# Base User Page
def base_user_page(request):
    return render(request, 'Users/base_users_page.html')

# This function show send product form.
def users_send_product(request):
    all_ds = exec_data.getAllDS()
    context_return = {'all_DS' : all_ds }

    if request.method == 'POST':
        lst_error = []
        dict_para_exec = {}
        
        dict_para_exec['idUser'] = request.session.get('id_role_user_ddelivery', None)

        # Information about sender
        dict_para_exec['nameSender'] = request.POST.get('inputSenderName', None)
        dict_para_exec['telNumSender'] = request.POST.get('inputSenderTelNum', None)
        dict_para_exec['provinceAddrSender'] = request.POST.get('chooseAddProvinceSender', None)
        dict_para_exec['districtAddrSender'] = request.POST.get('chooseAddDistrictSender', None)
        dict_para_exec['wardAddrSender'] = request.POST.get('chooseAddWardSender', None)
        dict_para_exec['typeAddrSender'] = request.POST.get('typeAddressSender', None)
        dict_para_exec['noteAddrSender'] = request.POST.get('noteAddressSender', None)

        # Information about receiver
        dict_para_exec['nameReceiver'] = request.POST.get('inputReceiverName', None)
        dict_para_exec['telNumReceiver']  = request.POST.get('inputReceiverTelNum', None)
        dict_para_exec['provinceAddrReceiver']  = request.POST.get('chooseAddProvinceReceiver', None)
        dict_para_exec['districtAddrReceiver'] = request.POST.get('chooseAddDistrictReceiver', None)
        dict_para_exec['wardAddrReceiver'] = request.POST.get('chooseAddWardReceiver', None)
        dict_para_exec['typeAddrReceiver'] = request.POST.get('typeAddressReceiver', None)
        dict_para_exec['noteAddrReceiver'] = request.POST.get('noteAddrReceiver', None)

        # Input tag html support required so we don't need to check blank fill
        # In the simple case we just need to check user input address
        if (dict_para_exec['provinceAddrSender'] == 'NotProvince'):
            lst_error.append('You not choose country sender')
        if (dict_para_exec['districtAddrSender'] == 'NotDistrict'):
            lst_error.append('You not choose district sender')
        if (dict_para_exec['wardAddrSender'] == 'NotWard'):
            lst_error.append('You not choose ward sender')
        if (dict_para_exec['provinceAddrReceiver'] == 'NotProvince'):
            lst_error.append('You not choose country receiver')
        if (dict_para_exec['districtAddrReceiver'] == 'NotDistrict'):
            lst_error.append('You not choose district receiver')
        if (dict_para_exec['wardAddrReceiver'] == 'NotWard'):
            lst_error.append('You not choose ward receiver')

        if lst_error:
            return redirect('Users_app:Users_send_product_page', error_send_product = lst_error)
        
        # We get information about shipping cost and cod cost
        dict_para_exec['shippingCost'] = request.POST.get('inputShippingCost', None)
        dict_para_exec['codCost'] = request.POST.get('inputCODCost', None)
        dict_para_exec['whoPayCost'] = request.POST.get('whoPayCost', None)
        dict_para_exec['chooseDS'] = request.POST.get('chooseDS', None)

        # Each list contain : productName, typeProduct, quantityProduct, weightProduct, sizeProduct, descriptionProduct 
        # Each order can contain many product so we create 1 list to store all product, 1 product is 1 list
        lst_all_product = []

        order_code_random = datetime.datetime.now().strftime(f"%Y%m%d%H%M%S") + 'User' + str(dict_para_exec['idUser']) + dict_para_exec['telNumSender'] + dict_para_exec['telNumReceiver']

        for index in range(0, int(request.POST.get('allProductAdd'))):
            lst_all_product.append([request.POST.get(f'productName{index}'), 
            request.POST.get(f'chooseTypeProduct{index}'),request.POST.get(f'productQuantity{index}'), request.POST.get(f'productWeight{index}'),
            request.POST.get(f'productSize{index}'), request.POST.get(f'descriptionProduct{index}')])
            img_product = request.FILES[f'imageProduct{index}']
            # uploadImageFirebase(img_product, f'User/UserProvideImage/{order_code_random}.jpg')
        
        dict_para_exec['lstAllProduct'] = lst_all_product

        exec_data.exec_users_send_product(dict_para_exec['idUser'], order_code_random, **dict_para_exec)

        context_return['notificationNewOrder'] = f'Create success New Order. Code Order is {order_code_random}. You can check it on order in pending tab'

        return render(request, 'Users/users_send_product.html', context_return)

    return render(request, 'Users/users_send_product.html', context_return)

def return_order(request, current_page = 1):
    id_user = request.session.get('id_role_user_ddelivery', None)
    
    get_return_order = exec_data.get_return_order(id_user, current_page)
    paginationPage = get_return_order['pagination']
    return_order = get_return_order['return_order']
    len_return_order = get_return_order['length_all_return_order']
    
    all_inform = get_inform_order.get_information(return_order)
    
    context_return = {'return_order' : return_order}
    context_return['lstSender'] = all_inform[0]
    context_return['lstReceiver'] = all_inform[1]
    context_return['lstProduct'] = all_inform[2]
    context_return['paginationPage'] = paginationPage
    context_return['CurrentPage'] = current_page
    context_return['len_all_order'] = len_return_order
    context_return['range_pagination_page'] = [iteration for iteration in range(1, paginationPage + 1)]
    
    return render(request, 'Users/order_return.html', context_return)

def users_logout(request):
    request.session.clear()
    return redirect('homepage_app:Homepage_homepage')

def users_search_order(request):
    if request.method == 'POST':
        id_user = request.session.get('id_role_user_ddelivery', None)
        code_order = request.POST.get('inputCodeOrder', None)

        get_order = exec_data.exec_search_order(id_user, code_order)
        all_inform = get_inform_order.get_information(get_order)

        context_return = {'getOrder' : get_order, 'lstSender' : all_inform[0], 'lstReceiver' : all_inform[1], 'lstProduct' : all_inform[2]}

        return render(request, 'Users/users_search_order.html', context_return)

    return render(request, 'Users/users_search_order.html')

def base_personal_profile(request):
    id_user = request.session.get('id_role_user_ddelivery', None)
    user_inform = exec_data.get_inform_users(id_user) 

    context_return = {}

    context_return['userInform'] = user_inform

    if request.method == 'POST':
        form_data = request.POST

        if 'submitBasicInform' in form_data:
            name_user = form_data['inputNameUser']
            tel_user = form_data['inputTelUser']
            gmail_user = form_data['inputGmailUser']
            gender_user = form_data['inputGenderUser']

            status_update = exec_data.update_basic_inform_user(id_user, name_user, tel_user, gmail_user, gender_user)
            if status_update == 'OK':
                context_return['notificationMsg'] = 'Update basic information success'
                return render(request, 'Users/users_personal_profile.html', context_return)
            else:
                context_return['notificationMsg'] = 'Update basic information fail'
                return render(request, 'Users/users_personal_profile.html', context_return)
        elif 'submitAdvanceInform' in form_data:
            province_user = form_data['chooseProvinceUserProfile']
            district_user = form_data['chooseDistrictUserProfile']
            ward_user = form_data['chooseWardUserProfile']
            
            if province_user == 'NotProvince' or district_user == 'notDistrict' or ward_user == 'NotWard':

Users/templates/Users/base_users_page.html
<!-- Comment block -->
{% load static %}

<link rel="stylesheet" href="{% static 'Users/css/base_users_page.css' %}">
<script src="{% static 'Users/javascript/base_users_page.js' %}"></script>

<div class="header__page">
    <header>
        <div class="logo__header">
            <a href="{% url 'Users_app:Users_base_user_page' %}" class="link__to__nagivation">
                <img src="{% static 'Users/images/Logo.png' %}" alt="logo" id="header__logo__image">
            </a>
        </div>
        <div class="header__menu">
            <div class="header__menu__language">
                <p id="header__menu__language__title">Ngôn ngữ</p>
                <div class="choose__language__header">
                    <p class="each__language__title">Việt Nam</p>
                    <p class="each__language__title">English</p>
                </div>
            </div>

            <ul class="menu__header">
                <li class="menu__header__item">
                    <a href="#" class="menu__header__title">Menu</a>
                    <div class="menu__header__child">
                        <div class="menu__header__child__item">
                            <h4>Order</h4>
                            <ul class="menu__child__list">
                                <li><a href="{% url 'Users_app:Users_static_order_pending' 1 %}" class="link__to__nagivation">In Pending</a></li>
                                <li><a href="{% url 'Users_app:Users_static_order_need_delivery' 1 %}" class="link__to__nagivation">Need Delivery</a></li>
                                <li><a href="{% url 'Users_app:Users_static_order_delivery' 1 %}" class="link__to__nagivation">In Delivery</a></li>
                                <li><a href="{% url 'Users_app:Users_static_order_success' 1 %}" class="link__to__nagivation">Success</a></li>
                                <li><a href="{% url 'Users_app:Users_return_order' 1 %}" class="link__to__nagivation">Return Order</a></li>
                            </ul>
                        </div>
                        <div class="menu__header__child__item">
                            <h4>Static</h4>
                            <ul class="menu__child__list">
                                <li><a href="{% url 'Users_app:Users_show_all_order' 1 %}" class="link__to__nagivation">All Order</a></li>
                                <li><a href="{% url 'Users_app:Users_static_order_by_date' 1 None %}" class="link__to__nagivation">Day</a></li>
                            </ul>
                        </div>
                        <div class="menu__header__child__item">
                            <h4>Search Order</h4>
                            <ul class="menu__child__list">
                                <li><a href="{% url 'Users_app:Users_search_order' %}" class="link__to__nagivation">Search Order</a></li>
                            </ul>
                        </div>
                        <div class="menu__header__child__item">
                            <h4>Profile</h4>
                            <ul class="menu__child__list">
                                <li><a class="link__to__nagivation" href="{% url 'Users_app:Users_personal_profile_homepage' %}">Edit Profile</a></li>
                            </ul>
                        </div>
                    </div>
                </li>
                <li>
                    <a href="{% url 'Users_app:Users_send_product_page' %}" class="link__to__nagivation send__product__menu">Send Product</a>
                </li>
                <li>
                    <a href="{% url 'Users_app:Users_log_out' %}" class="link__to__nagivation log__out__menu">Log out</a>
                </li>
            </ul>
        </div>
    </header>
</div>
<!-- End of comment block -->

{% block contentHomepageUser %}
    {% if name_user %}
        <div class="homepage__userpage">
            <div>
                <h1>Hello User : {{name_user}}</h1><br>
                <p>Bạn muốn đặt giao hàng gì hôm nay nào ?</p>
                <div class="homepage__userpage__link__to__diff__tab">
                    <a href="#">Send Product</a>
                    <a href="#">Search Order</a>
                    <a href="#">All Order</a>
                </div>
            </div>
            <img src="{% static 'Users/images/Logo.png' %}" alt="Image homepage">
        </div>
    {% endif %}
{% endblock %}
{% block contentUserPage %}
{% endblock %}
<footer>
    <div class="footer__inner">
        <div class="footer__item">
            <h3>Order</h3>
            <a href="#" class="footer_link">In Pending</a>
            <a href="#" class="footer_link">Need Delivery</a>
            <a href="#" class="footer_link">In Delivery</a>
            <a href="#" class="footer_link">Success</a>
            <a href="#" class="footer_link">Return Order</a>
        </div>
        <div class="footer__item">
            <h3>Static</h3>
            <a href="#" class="footer_link">All Order</a>
            <a href="#" class="footer_link">Day</a>
        </div>
        <div class="footer__item">
            <h3>Search Order</h3>
            <a href="#" class="footer_link">Search Order</a><br><hr><br>
            <h3>SendProduct</h3>
            <a href="#" class="footer_link">Send Product</a>
        </div>
        <div class="footer__item">
            <img src="{% static 'Users/images/Logo.png' %}" alt="logo" id="footer__logo__image">
            <p class="footer__inform__company">Address : Hồ Chí Minh City</p>
            <p class="footer__inform__company">Tel : 123456789</p>
        </div>
    </div>
</footer>

Users/templates/Users/order_return.html
{% extends 'Users/static_user.html' %}
{% load custom_filters %}
{% load static %}

{% block eachStaticDetail %}
    <script src="{% static 'Users/javascript/static_order.js' %}"></script>
    <link rel="stylesheet" href="{% static 'Users/css/static_order.css' %}">
    <link rel="stylesheet" href="{% static 'Users/css/return_order.css' %}">
    <script>
        var CurrentPage = parseInt('{{CurrentPage}}')
        var paginationPage = parseInt('{{paginationPage}}')
        document.onreadystatechange = function(){
            if (document.readyState === 'interactive') {
                onPageLoadPagination();
            }
        }
    </script>
    <div class="show__content__page">
        <p>All order return:</p>
    </div>
    <div class="show__order__return">
        {% if return_order %}
            {% if return_order|length == 0 %}
                <p class="not__found__any__order__title">Not found any order</p>
            {% else %}
                <table>
                    <tr>
                        <th>No</th>
                        <th>Code Order</th>
                        <th>Sender</th>
                        <th>Receiver</th>
                        <th>Product Name</th>
                        <th>Total Cost</th>
                        <th>Status</th>
                        <th>Note</th>
                        <th>Date Create</th>
                    </tr>
                    {% for order in return_order %}
                        <tr>
                            <td>{{forloop.counter}}</td>
                            <td><div class="show__code__order" data-content="{{order.code_order_delivery}}">{{order.code_order_delivery}}</div></td>
                            <td>
                                {% for sender in lstSender|get_list_item:forloop.counter0 %}
                                    <p>Name : <span>{{sender.name}}</span></p>
                                    <p>Telephone number : <span>{{sender.tel_num}}</span></p>
                                    <p>Address : <span>{{sender.ward}}, {{sender.district}}, {{sender.province}}</span></p>
                                {% endfor %}
                            </td>
                            <td>
                                {% for receiver in lstReceiver|get_list_item:forloop.counter0 %}
                                    <p>Name : <span>{{receiver.name}}</span></p>
                                    <p>Telephone number : <span>{{receiver.tel_num}}</span></p>
                                    <p>Address : <span>{{receiver.ward}}, {{receiver.district}}, {{receiver.province}}</span></p>
                                {% endfor %}
                            </td>
                            <td>
                                {% for product in lstProduct|get_list_item:forloop.counter0 %}
                                    <p>Product {{forloop.counter}} : {{product.name_product}}</p>
                                {% endfor %}
                            </td>
                            <td>
                                {{order.total_cost}}
                            </td>
                            <td>{{order.status_order}}</td>
                            <td>{{order.note}}</td>
                            <td>{{order.date_create}}</td>
                        </tr>
                    {% endfor %}
                </table>
                <div class="pagination__show__all__order">
                    {% if paginationPage > 5 %}
                        <button id="btn__first__pagination__page" onclick="firstPagePagination()">Go to page 1</button>
                        <button id='btn__previous__pagination' onclick="previousBtnPagination()">Previous</button>
                        {% for pagination in range_pagination_page %}
                            {% if CurrentPage == pagination %}
                                <a href="{% url 'Users_app:Users_return_order' pagination %}">
                                    <button class="btn__pagination active__btn__pagination" id="btn__page__pagination__page{{pagination}}">{{pagination}}</button>
                                </a>
                            {% else %}
                                <a href="{% url 'Users_app:Users_return_order' pagination %}">
                                    <button class="btn__pagination" id="btn__page__pagination__page{{pagination}}">{{pagination}}</button>
                                </a>
                            {% endif %}
                        {% endfor %}
                        <button id="btn__next__pagination" onclick="nextBtnPagination()">Next</button>
                        <button id="btn__end__pagination__page" onclick="lastPagePagination()">Go to page end</button>
                    {% else %}
                        {% for pagination in range_pagination_page %}
                            {% if CurrentPage == pagination %}
                                <a href="{% url 'Users_app:Users_return_order' pagination %}">
                                    <button class="btn__pagination active__btn__pagination" id="btn__page__pagination__page{{pagination}}">{{pagination}}</button>
                                </a>
                            {% else %}
                                <a href="{% url 'Users_app:Users_return_order' pagination %}">
                                    <button class="btn__pagination" id="btn__page__pagination__page{{pagination}}">{{pagination}}</button>
                                </a>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                </div>
            {% endif %}
        {% endif %}
    </div>
{% endblock %}

Users/templates/Users/show_img_firebase_user.html
{% if imageShow %}
    <img src="data:image/jpeg;base64,{{imageShow}}" alt="Image" width="500px">
{% elif errorShowImage %}
    <p>{{errorShowImage}}</p>
{% else %}
    <p>Maybe, you don't give code Order success</p>
{% endif %}

Users/templates/Users/static_user.html
{% extends 'Users/base_users_page.html' %}
{% load static %}

{% block contentUserPage %}
    <div class="static__page__userpage">
        <link rel="stylesheet" href="{% static 'Users/css/static_users.css' %}">
        <div class="show__all__btn__static__user">
            <div class="show__btn__static__inner">
                <form method="post" class="form__btn__static">
                    {% csrf_token %}
                    <input type="submit" name = 'showAllOrder' value='Show All Product' class="btn__static static__show__all__btn"></input>
                    <input type="submit" name = 'showOrderByDate' value="Show order by date" class="btn__static static__by__date"></input>
                    <input type="submit" name = 'summaryOrder' value='Summary order' class="btn__static static__by__status"></input>
                </form>
            </div>
        </div>
        <div class="show__chart__image">
            {% if pieChart %}
                <img id='image__pie__chart' src="data:image/png;base64,{{ pieChart }}" alt="Image chart">
            {% endif %}
        </div>
    </div>
{% block eachStaticDetail %}
{% endblock %}
{% endblock %}  